id: P010322
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG18490
  title: སེམས་ངོ་མཛུབ་ཚུགས་ཀྱི་གདམས་པའི་གནད་འགྲོལ་སྐྱབས་རྗེ་བླ་མ་པདྨ་སྐལ་བཟང་གི་ཞལ་རྒྱུན།
  author: ''
  volumes:
    05f7b6b3cc6a482e94fdfed560853bc9:
      image_group_id: I1KG18509
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
